#ifndef KEYBOARD_CLASSIC_H
#define KEYBOARD_CLASSIC_H

#define KEYBOARD_CLASSIC_KEY_RELEASED 0x80
#define KEYBOARD_CLASSIC_ISR_KEYBOARD_INTERRUPT 0x21
#define KEYBOARD_CLASSIC_INPUT_PORT 0x60
struct keyboard *keyboard_classic();

#endif